# Generated by Django 4.2.6 on 2023-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='job_type',
            field=models.CharField(blank=True, choices=[('C', 'CEO'), ('ET', 'English Teacher'), ('M', 'Marketer'), ('MA', 'Manager'), ('MT', 'Math Teacher'), ('AS', 'Assistant'), ('BT', 'Backend Teacher'), ('FT', 'Frontend Teacher'), ('SMM', 'SMM Teacher'), ('TT', 'Trading Teacher')], default='AS', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default='+998', null=True),
        ),
    ]
