# Generated by Django 4.2.6 on 2023-10-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_age_alter_usermodel_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
