# Generated by Django 4.2.6 on 2023-10-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='card_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
