# Generated by Django 4.2.6 on 2023-10-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_salarypaymentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypaymentsmodel',
            name='amount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
