# Generated by Django 4.2.6 on 2023-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_salarypaymentsmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypaymentsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
