# Generated by Django 4.2.6 on 2023-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('repaying_date', models.DateField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_or_what', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
            ],
        ),
    ]
