# Generated by Django 4.2.6 on 2023-10-16 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesmodel_groupsmodel_paymentsmodel_studentsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmodel',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10), default=[], size=None),
        ),
    ]
