# Generated by Django 4.2.6 on 2023-10-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_groupsmodel_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.coursesmodel'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.studentsmodel'),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.groupsmodel'),
        ),
    ]
