# Generated by Django 4.2.6 on 2023-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_groupsmodel_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
