# Generated by Django 4.2.6 on 2023-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_paymentsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='age',
            field=models.BigIntegerField(),
        ),
    ]
